[package]
name = "word-count"
version = "0.1.0"
edition = "2021"
description = "一个简单的单词计数工具"
repository = "https://github.com/cline0/WordCount.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ={ version = "4.5.4"}